server:
  port: 8091

spring:
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    enabled: true
    service-url.defaultZone: http://localhost:7000/eureka/

management:
  endpoints:  
    web:
      exposure:
        include: refresh
        
message: hello from git, new version








